### ISSUE TITLE
TODO for v1.0.0

### ISSUE THREAD

**Issue by neuecc** [Cysharp/AlterNats#1]
- [x] Options.Url(parse multiple Host/Port)
- [x] Retry and Jitter delay for reconnect
- [x] Ping Loop
- [x] Redefine ObjectPool
- [x] Auto Connect
- [x] ReaderLoop Skip to receive invalid data
- [x] ConnectionPool
- [x] Publish NullSignal
- [x] RequestAsync supports exception
- [x] Improve Request/Response
- [x] Timeout
- [x] ThreadPoolWorkItem logging
- [x] Handling disconnecting and writer promise
- [x] Add DiagnosticsCounter
- [x] Callbacks for connection event
- [x] Timeout for req/res
- [x] ConfigureAwait(false)
- [x] UnitTests
- [x] UseNats (AlterNats.Hosting)
- [ ] Document
